#!/bin/bash
set -e

# 0. Tests must pass
echo "[deploy] Running tests..."
if ! npm test; then
  echo "[deploy] BLOCKED: tests failed. Fix before deploying."
  exit 1
fi

# --- DEPLOY GATE ---

# 1. Must be on main
BRANCH=$(git branch --show-current)
if [ "$BRANCH" != "main" ]; then
  echo "[deploy] BLOCKED: must be on main (currently on '$BRANCH')"
  exit 1
fi

# 2. No uncommitted changes (ensures deployed code = committed code)
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "[deploy] BLOCKED: uncommitted changes detected. Commit first."
  exit 1
fi

# 3. Local includes all remote work (prevents deploying without latest fixes)
git fetch origin main --quiet
REMOTE=$(git rev-parse origin/main)
if ! git merge-base --is-ancestor "$REMOTE" HEAD 2>/dev/null; then
  echo "[deploy] BLOCKED: origin/main has commits not in local. Run: git pull"
  exit 1
fi

# 4. Version regression check (ensures you're not deploying older code)
LAST_DEPLOYED=$(grep "WORKER_VERSION" src/version.ts | grep -oE "'[a-f0-9]+'" | tr -d "'")
if [ -n "$LAST_DEPLOYED" ]; then
  if ! git merge-base --is-ancestor "$LAST_DEPLOYED" HEAD 2>/dev/null; then
    echo "[deploy] BLOCKED: HEAD is not a descendant of last deployed version ($LAST_DEPLOYED)"
    echo "         This would be a version regression. Merge latest main first."
    exit 1
  fi
fi

# --- DEPLOY ---
HASH=$(git rev-parse --short HEAD)
echo "// Auto-generated by deploy.sh. Do not edit manually." > src/version.ts
echo "export const WORKER_VERSION = '${HASH}';" >> src/version.ts

echo "[deploy] Passed all gates. Deploying version: ${HASH}"
npx wrangler deploy

echo "[deploy] SUCCESS: ${HASH} is now live."

# --- POST-DEPLOY ---
git push origin main --quiet
echo "[deploy] Pushed to origin/main."
