#!/bin/bash
set -e

# Generate version tag from current git short hash
HASH=$(git rev-parse --short HEAD)
echo "// Auto-generated by deploy.sh. Do not edit manually." > src/version.ts
echo "export const WORKER_VERSION = '${HASH}';" >> src/version.ts

echo "[deploy] Worker version: ${HASH}"
npx wrangler deploy
